# Generated by Django 6.0.2 on 2026-02-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_lms", "0002_h5pactivity_lessonpage_h5pattempt_h5pxapistatement"),
    ]

    operations = [
        migrations.CreateModel(
            name="H5PContentUserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=255)),
                ("sub_content_id", models.PositiveIntegerField(default=0)),
                ("value", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_user_data",
                        to="wagtail_lms.h5pattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "H5P Content User Data",
                "verbose_name_plural": "H5P Content User Data",
                "unique_together": {("attempt", "data_type", "sub_content_id")},
            },
        ),
    ]
