# Generated by Django 4.2 on 2026-02-23 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_lms", "0006_cleanup_stale_contenttypes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="h5plessonpage",
            options={"verbose_name": "H5P lesson page"},
        ),
        migrations.AlterModelOptions(
            name="scormlessonpage",
            options={"verbose_name": "SCORM lesson page"},
        ),
    ]
